# Header
menu:
  Home: /
  Archives: /archives

# Sidebar
sidebar: right

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tag
- tagcloud
- archive_cloud

# widget behavior
archive_type: 'monthly'
show_count: false

# Fancybox
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: